### ISSUE TITLE
iptsd in chromeos

### ISSUE THREAD

**Issue by sebanc** [kitakar5525/linux-kernel#3]
Hi Hayataka,

I have finally found a fix for older devices (Intel Gen < skylake) to boot brunch with kernel 5.4 and in preparation to switch brunch to kernel 5.4 I am trying to implement the new ipts method with iptsd in chromeos.

I currently have both ipts kernel part and iptsd built correctly (as far as I can tell) and I can see input which looks correct in "evtest" but touches are not recognized in chromeos.

I was wondering if you used a specific iptsd patch in your chromeos iptsd implementation ?

Between, I have been reading the progress on the camera support and you and the other participants are really doing great ! Thanks for that :)

**Comment by kitakar5525** [comment]
> I have finally found a fix for older devices (Intel Gen < skylake) to boot brunch with kernel 5.4 and in preparation to switch brunch to kernel 5.4 I am trying to implement the new ipts method with iptsd in chromeos.
> 
> I currently have both ipts kernel part and iptsd built correctly (as far as I can tell) and I can see input which looks correct in "evtest" but touches are not recognized in chromeos.
> 
> I was wondering if you used a specific iptsd patch in your chromeos iptsd implementation ?

Hi sebanc,

I also noticed that iptsd won't work as-is. I have [this patch](https://github.com/kitakar5525/chromeos-kernel-linux-surface/blob/7008458032ad3b908c5ca46ebd3912ed9cda3afd/patch-to-os-image/iptsd/0001-finger-multitouch-also-set-ABS_X-and-ABS_Y.patch)
This patch is written for the older iptsd written in Go, before switching to C. But the basics are the same I guess.

It's not complete yet, but at least it enables finger touch input other than taps in chrome browser (you can now scroll, pinch-to-zoom, long-tap, ...). Looks like it's fully working on ARC at a glance, including taps.

I haven't opened an issue on iptsd repo and even haven't told this issue to StollD yet, because I've been obsessed with cameras and the other things these days :D
So, I'd appreciate it a lot if you can discuss this issue with StollD.

A prebuilt binary is also available [here](https://github.com/kitakar5525/chromeos-kernel-linux-surface/blob/master/patch-to-os-image/iptsd/iptsd-v0.1-2-gbcb2516%2B0001-finger-multitouch-also-set-ABS_X-and-ABS_Y-ROOT_C.tar.gz)

> Between, I have been reading the progress on the camera support and you and the other participants are really doing great ! Thanks for that :)

Thanks :)

**Comment by kitakar5525** [comment]
I made the patch by comparing the `evtest` output on v4.19-ipts and this iptsd and saw what `Event code` are missing.
If I remember correctly, the iptsd still lacks some `Event code`, but I gave up adding it before as it seems to be difficult for me :D

**Comment by sebanc** [comment]
Thanks for the detailed explanation and the patch :)

This patch is still very mysterious for me as I only looked at old ipts code but never really investigated the hid events.

I will raise an issue on iptsd and hopefully StollD will be able to help.

Thanks a lot for all this info and best of luck with your other projects !

**Comment by kitakar5525** [comment]
> Thanks for the detailed explanation and the patch :)

No problem :)

> I will raise an issue on iptsd and hopefully StollD will be able to help.

Thanks!
